#!/bin/bash
#!bin/sh

FUNC="-open -prev -cp"
ARGS="$#"
echo $ARGS

for i in 'seq $ARGS 2';
do
	FIN="${2%%.*}"
	FILET="$FILE\ $FIN"
done
FILE="$FILET.pdf" 
echo $FILE
if [[ $FUNC != *"$1"* ]] ; then
	printf "List of functions: $FUNC\n" 
elif [[ ! -f $FILE ]] ; then
	echo "ERROR: File does not exist!"
elif [[ "-open" == "$1" ]] ; then
	case $OSTYPE in
	linux-gnu)
		echo "Opening in Linux Distribution"
		gnome-open "$FILE"
	;;
	darwin*)
		echo "Opening in Mac OSX"
                open "$FILE"
	esac
elif [[ "-prev" == "$1" ]] ; then
	more "$FILE"
elif [[ "-cp" == "$1" ]] ; then
        printf "Specify the location to copy:"
	read LOCAL
	cp "$FILE" $LOCAL
fi
